version: '2.0'


services:
  db:
    image: mysql:5.7.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: userservice

  adminer:
    image: adminer
    ports:
        - 8080:8080
    restart: always

  userservice:
     image: shaldnikita/userservice
     restart: always
     ports:
        - 9000:8080
     environment:
        MYSQL_ROOT_PASSWORD : 123
        MYSQL_DATABASE: userservice
        MYSQL_PORT: 3306

