spring:
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE:test}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect

